hint = '歡迎使用遊戲小助手\n我們提供以下遊戲活動查詢\n可以輸入代號或遊戲簡稱：\n1. 神魔之塔\n2. FGO\n3. RO\n4. 傳說對決\n5. 天堂M\n6. 寶可夢'
helps = ['GInfo', 'ginfo', 'GINFO', 'help', '搜尋', '指令', '參數', 'Help']
ts = ['1', '神魔之塔', '神魔', 'ts', 'Ts', 'TS', '神抄之塔', '神抄']
ro = ['2', 'RO', '守護永恆', '守護永恆的愛', '仙境傳說', 'RO仙境傳說', '仙境', 'ro']
fgo = ['3', 'FGO', 'Fate', 'Fate/Grand Order', 'FATE/GRAND ORDER', 'FATE', 'fgo']
aov = ['4', 'AOV', 'aov', '傳說', '傳說對決', 'AoV']
lineageM = ['5', '天堂M', '天堂', 'LineageM', 'lineagem']
pokemongo = ['6', 'PokemonGo', 'pokemongo', '寶可夢', 'pokemon', 'Pokemon', '寶可']
activity_order = ['Lastest Activity', 'Second Activity', 'Third Activity', 'Fourth Activity', 'Fifth Activity']